server:
  port: 8092
  servlet:
    context-path: /property-view

spring:
  application:
    name: hotel-management-service

  profiles:
    active: h2

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha